Edits DZ
Gendina17/DZ pull request #1
Opened 2020-03-23 12:10 UTC by Gendina17

2020-03-23 12:40 UTC, maksimuimin requested changes
Название fragmentFirst - выпилить из проекта.

2020-03-23 12:40 UTC, DragonF0rm commented on app/src/main/java/com/gendina/hw/FragmentFirst.java
> +    public static int element_count = 0;
Плохое решение. Количество элементов - это не статическое поле, оно может различаться у разных инстансов фрагмента.

2020-03-23 12:40 UTC, DragonF0rm commented on app/src/main/java/com/gendina/hw/FragmentFirst.java
> +            resurse.add(new Data(Integer.toString(j)));}
Что тут с выравниванием произошло? Такое читать очень сложно. Пожалуйста, относись к коду более аккуратно. Обычно предполагается, что его потом читать многим другим людям

2020-03-23 12:40 UTC, DragonF0rm commented on app/src/main/java/com/gendina/hw/MainActivity.java
> +private static final int FINAL_COUNT=101;
Что такое 101? Название переменной не позволяет это понять. Если это начальное количество элементов списка, то их не 101, а 100.

2020-03-23 12:40 UTC, DragonF0rm commented
Почему у тебя 2 файла класса FragmentFirst в проекте?

2020-03-23 12:41 UTC, DragonF0rm commented
А ещё не нужно смешивать CamelCase и snake_case, когда выбираешь названия переменных. В Java принят CamelCase, так что все snake_case переменные - переименовать.

2020-03-24 08:21 UTC, Gendina17 commented on app/src/main/java/com/gendina/hw/FragmentFirst.java
> +    public static int element_count = 0;
Изменено, static убрано

2020-03-24 08:25 UTC, Gendina17 commented on app/src/main/java/com/gendina/hw/MainActivity.java
> +private static final int FINAL_COUNT=101;
Изменено

2020-03-24 15:53 UTC, DragonF0rm commented on app/src/main/java/com/gendina/hw/FragmentFirst.java
> +    public static int element_count = 0;
Принто

2020-03-24 15:53 UTC, DragonF0rm commented on app/src/main/java/com/gendina/hw/FragmentFirst.java
> +            resurse.add(new Data(Integer.toString(j)));}
Принято

2020-03-24 15:53 UTC, DragonF0rm commented on app/src/main/java/com/gendina/hw/MainActivity.java
> +private static final int FINAL_COUNT=101;
Принято

2020-03-24 16:03 UTC, maksimuimin approved these changes
Можно мёрджить

2020-03-24 16:53 UTC, merged